### ISSUE TITLE
Error with repo

### ISSUE THREAD

**Issue by chibisov** [AllMyChanges/original.allmychanges.com#2]
https://github.com/designmodo/bootstrap

**Comment by chibisov** [comment]
`
22:48:09 TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/web-chib/allmychanges_project/env/local/lib/python2.7/site-packages/rq/worker.py", line 411, in perform_job
    rv = job.perform()
  File "/home/web-chib/allmychanges_project/env/local/lib/python2.7/site-packages/rq/job.py", line 348, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/web-chib/allmychanges_project/allmychanges/tasks.py", line 12, in update_repo
    repo._update()
  File "/home/web-chib/allmychanges_project/allmychanges/models.py", line 94, in _update
    self._update_from_filename(full_filename)
  File "/home/web-chib/allmychanges_project/allmychanges/models.py", line 117, in _update_from_filename
    changes = _parse_changelog_text(f.read())
  File "/home/web-chib/allmychanges_project/crawler/__init__.py", line 94, in _parse_changelog_text
    current_section['items'].append(current_item)
TypeError: 'NoneType' object has no attribute '__getitem__'
`

**Comment by chibisov** [comment]
https://github.com/faif/python-patterns/

**Comment by chibisov** [comment]
https://github.com/JackStouffer/Flask-Foundation

**Comment by chibisov** [comment]
Виснет на https://github.com/pydanny/django-admin2

**Comment by svetlyak40wt** [comment]
Работает, не повторяется, а про django-admin я новый тикет открою
